### ISSUE TITLE
How to call the released version

### ISSUE THREAD

**Issue by sathanu** [willeponken/stat-webview#2]
I am new to QT and c++. I have used the code. It is working fine when running in qt creator tool. 
but when i run the generated *.exe file it show exection.

Please see the error

![qtwebview_error](https://user-images.githubusercontent.com/20484984/38877134-a333aea0-427b-11e8-9e9d-4c6a4d9785fb.png)

**Comment by wstrm** [comment]
Hello there, sorry but I do not use Windows. But a wild guess would be that you need to generate some kind of installer for the application?
